# Generated by Django 5.1.5 on 2025-02-05 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_alter_postimage_post_comment_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='tag',
            field=models.CharField(max_length=100, unique=True, verbose_name='태그'),
        ),
    ]
